---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, system manager, unsupported features, on-premises ONTAP in NetApp Console 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하세요. 
---
= NetApp 콘솔에서 온프레미스 ONTAP 클러스터를 관리하는 데 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하세요.



== ASA r2 시스템과 관련된 제한 사항

NetApp ASA r2 시스템을 검색한 후 시스템 관리자로 이동하게 됩니다.

ASA r2 시스템에서는 다른 관리 옵션을 사용할 수 없습니다.  표준 보기를 사용할 수 없고 NetApp 데이터 서비스를 활성화할 수 없습니다.

https://docs.netapp.com/us-en/asa-r2/index.html["ASA r2 시스템에 대해 자세히 알아보세요"^]



== 지원되지 않는 클러스터

SAML 인증으로 구성된 온프레미스 ONTAP 클러스터는 콘솔에서 지원되지 않습니다.



== 시스템 관리자 제한 사항

다음 시스템 관리자 기능은 콘솔에서 지원되지 않습니다.

* 클러스터 설정
+
온프레미스 ONTAP 클러스터에서 관리 IP 주소를 설정하고 관리자 비밀번호를 구성한 후 콘솔에서 클러스터를 검색할 수 있습니다.

* 역할 기반 액세스 제어(콘솔 에이전트만 해당)
+
콘솔 에이전트를 사용하여 온프레미스 ONTAP 클러스터를 검색하고 관리하는 경우 System Manager의 역할 기반 액세스 제어는 지원되지 않습니다.  검색 과정에서 관리자 자격 증명을 입력하라는 메시지가 표시됩니다.  해당 자격 증명은 시스템 관리자에서 수행되는 모든 작업에 사용됩니다.

+
직접 검색 옵션을 사용하면 콘솔에서 시스템을 열 때마다 ONTAP 자격 증명으로 로그인하라는 메시지가 표시됩니다.

* NetApp 백업 및 복구 활성화
+
System Manager에서 백업 및 복구를 활성화하려면 클러스터 버전이 9.13.1이어야 합니다.

+
콘솔 에이전트를 사용하여 클러스터를 발견하지 못했다면 시스템 관리자(고급 보기)를 사용하여 백업 및 복구를 활성화할 수 없습니다.  하지만 온프레미스 클러스터에서 백업 및 복구를 콘솔에서 직접 활성화할 수 있습니다. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["시작하는 방법을 알아보세요"^]

* 주문형 업그레이드
+
클러스터 버전이 ONTAP 9.9.1 이하인 경우 펌웨어 및 소프트웨어의 주문형 업그레이드를 이용할 수 없습니다.

+
콘솔 에이전트가 없으면 로컬 머신에서 업데이트를 할 수 없고, 콘솔을 사용하여 액세스할 수 있는 서버에서만 업데이트를 할 수 있습니다.

* 글로벌 검색
* 사용자 인터페이스 설정

